implement runm object get command
Adds a new `runm object get <search>` command that accepts either a UUID
or name and looks up a single object record. If a name is specified
instead of a UUID, then the --type flag is required.

```
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh object get
8dd1e156a27e43c7b17543221c999912
Partition: ace2f2f1016c4922ac0be16cad6a32f2
Type:      runm.image
UUID:      8dd1e156a27e43c7b17543221c999912
Name:      db-server
Project:   proj0
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh object get
db-server
Error: --type required when <search> is not a UUID
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh object get
db-server --type runm.image
Partition: ace2f2f1016c4922ac0be16cad6a32f2
Type:      runm.image
UUID:      8dd1e156a27e43c7b17543221c999912
Name:      db-server
Project:   proj0
```

Issue #43