add `runm bootstrap` CLI command
Adds the client side of the bootstrap process, which creates a new
partition, supplying the one-time-use bootstrap token:

```
[jaypipes@uberbox runmachine]$ ./scripts/dump-etcd.sh
gsr/services/runmachine-metadata/172.17.0.3:10000
runm-test-metadata/runm-metadata//
runm-test-metadata/runm-metadata/bootstrap
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh bootstrap bootstrapme part0
1b561f953481442fb301a30f9c40994c
[jaypipes@uberbox runmachine]$ ./scripts/dump-etcd.sh
gsr/services/runmachine-metadata/172.17.0.3:10000
runm-test-metadata/runm-metadata//
runm-test-metadata/runm-metadata/partitions/by-name/part0
runm-test-metadata/runm-metadata/partitions/by-uuid/1b561f953481442fb301a30f9c40994c
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh bootstrap bootstrapme part0
Error: Bootstrap failed.
```

Note the bootstrap token is removed after successfully creating the
partition, and attempting to bootstrap again fails afterwards.

Issue #30