Add property schema document validation
Renames PropertySchema -> PropertyDefinition and breaks out the schema
element of a property definition.

Adds YAML and custom validation logic to PropertyDefinitionSet gRPC API
metadata service method, preventing malformed property schema documents
from being saved to storage:

```
[jaypipes@uberbox runmachine]$ cat tests/data/propschema.yaml
partition: part0
type: runm.machine
key: architecture
schema:
  blah
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh property-schema create -f tests/data/propschema.yaml
Error: [400002] invalid property schema for object type runm.machine and key architecture: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `blah` into types.PropertySchema.
[jaypipes@uberbox runmachine]$ cat tests/data/property-schemas/runm.machine-architecture.yaml
partition: part0
type: runm.machine
key: architecture
schema:
  type: string
  enum:
    - x86
    - x86_64
    - arm
    - arm64
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh property-schema create -f tests/data/property-schemas/runm.machine-architecture.yaml
Successfully created property schema
[jaypipes@uberbox runmachine]$ cat tests/data/property-schemas/invalid.yaml
partition: part0
type: runm.image
key: invalid
schema:
  type: array
[jaypipes@uberbox runmachine]$ ./scripts/exec-runm-command.sh property-schema create -f tests/data/property-schemas/invalid.yaml
Error: [400002] invalid property schema for object type runm.image and key invalid: invalid type array. valid types are [string integer number boolean].
```

Issue #21